### ISSUE TITLE
make terraform push changes from git commits

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/bezirksregionenprofile-daten#3]

**Comment by Lisa-Stubert** [comment]
This could be useful for us, as we are now working on this project again and going to add data soon. Do you have capacity to implement it?

**Comment by fabianmoronzirfas** [comment]
@Lisa-Stubert I’ll take a look. Would be good to bring you up on speed with a workflow like this so you don’t need me if something fails. 

Maybe we don’t need terraform for that. In the end it is an upload to AWS s3 might also work in a different way. 

I’m explore

**Comment by Lisa-Stubert** [comment]
@fabianmoronzirfas Ok thanks for exploring!

@tori-d FYI
